mongodb:
  image: mongo
  container_name: ngsi_mongo
  volumes:
    - ./data:/data/db

ngsi_encryption_layer:
  image: smartsdk/encryption-service-app
  container_name: ngsi_api
  ports:
    - "3900:3900"
  links:
    - mongodb:mongodb
  command: npm start
